### ISSUE TITLE
aliyun shadowsocks

### ISSUE THREAD

**Issue by pimkle** [yijingping/yijingping.github.io#1]
请问ip怎么获取 按照你教程操作了，ip拿的是阿里云控制台提供的ip，公用的私用的都试过了，连接失败

**Comment by yijingping** [comment]
那就用0.0.0.0
Jane Sheng <notifications@github.com>于2017年10月23日 周一上午3:18写道：

**Comment by pimkle** [comment]
用了0.0.0.0了 还是失败 防火墙什么的指令也敲进去了 telnet好像还是失败

**Comment by yijingping** [comment]
你用的哪里的机器，如果telnet失败 应该是服务没起来，或者被屏蔽了
Jane Sheng <notifications@github.com>于2017年10月23日 周一上午9:35写道：

**Comment by pimkle** [comment]
阿里云的 美国的

**Comment by yijingping** [comment]
加我微信jingpingyi 我给你看一下
Jane Sheng <notifications@github.com>于2017年10月23日 周一下午12:38写道：

**Comment by pimkle** [comment]
和作者讨论结果是这样的：aliyun海外服务区也全被禁了 🌝
